
#C:/temp/volumes/sql-server - Diretorio onde será armazenado os dados do sqlserver

services:
    sqlserver:
      image: mcr.microsoft.com/mssql/server
      hostname: sqlserver
      volumes:
        - C:/temp/volumes/sql-server:/var/opt/mssql/data
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Teste!@#
      ports:
        - "1433:1433"
